deployment:
  replicas: 1
  imageVersion: 1.0.0
  imageURL: 695862934667.dkr.ecr.us-east-1.amazonaws.com/roboshop/frontend
hpa:
  cpuUtilization: 15
tgb:
  arn: arn:aws:elasticloadbalancing:us-east-1:695862934667:targetgroup/roboshop-dev/7a2d6f1f5815a32b
